seed: 42
paths:
  raw_dir: data/raw
  proc_dir: data/processed
  features_dir: data/features
  models_dir: models
  reports_dir: reports
download:
  since: '2022'
regions:
  submercado: SE/CO
  carga_area: SECO
  meteo_points:
  - - -16.7
    - -49.3
  - - -15.9
    - -48.2
  - - -18.0
    - -49.7
  - - -13.6
    - -46.9
problem:
  horizon: weekly
  target_name: classe_risco
  forecast_horizon_weeks: 1
  label_rules:
    coluna_margem: margem_vs_carga_w
    q_baixo: 0.05
    q_medio: 0.2
    curtail_downgrade:
      usar_downgrade_cortes: true
      corte_ratio_thr: 0.05
      requer_saldo_importador_nao_positivo: true
    usar_override_hidro: true
    coluna_ear: ear_pct_mean_w
    coluna_ena: ena_mwmed_mean_w
    ear_q_baixo: 0.2
    ena_q_baixo: 0.2
    janelas_consecutivas_ena: 2
    usar_regras_duras: true
    reserva_operativa_frac: 0.05
    ens_ratio_thr: 0.05
    lolp_thr: 0.05
aggregation:
  freq: W
  features:
    daily_aggs:
    - mean
    - sum
    - max
    - min
    - std
    - p95
    - p05
    lags_weeks:
    - 1
    - 2
    - 4
    rolling_weeks:
    - 2
    - 4
    min_nonnull_ratio: 0.6
    min_nonnull_ratio_weekly: 0.6
modeling:
  holdout_fraction: 0.2
  metrics:
  - f1_macro
  - balanced_accuracy
  cv:
    type: TimeSeriesSplit
    n_splits: 5
  models:
  - name: logreg
    type: logistic_regression
    params:
      class_weight: balanced
      max_iter: 1000
      n_jobs: -1
    tuning:
      use: true
      method: grid
      cv_splits: 3
      refit: f1_macro
      scoring:
      - f1_macro
      - balanced_accuracy
      param_grid:
        C:
        - 0.1
        - 0.5
        - 1.0
        - 2.0
        - 5.0
        solver:
        - lbfgs
  - name: xgb
    type: xgboost
    params:
      n_estimators: 400
      learning_rate: 0.05
      max_depth: 4
      subsample: 0.9
      colsample_bytree: 0.8
      num_class: 3
      eval_metric: mlogloss
    tuning:
      use: true
      method: grid
      cv_splits: 3
      refit: f1_macro
      scoring:
      - f1_macro
      - balanced_accuracy
      param_grid:
        n_estimators:
        - 300
        - 500
        learning_rate:
        - 0.03
        - 0.06
        max_depth:
        - 3
        - 5
        subsample:
        - 0.8
        - 1.0
        colsample_bytree:
        - 0.7
        - 0.9
  class_weight_adjustments:
    baixo: 1.0
    medio: 1.0
    alto: 1.0
output:
  top_k_features: 25
